/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Fronted;

import Backend.Gestor;
import Backend.Solicitudes;
import javax.swing.JOptionPane;

/**
 *
 * @author xavi
 */
public class JInternalFrameAutorizacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameAutorizacion
     */
    
    Gestor gestor;
    public JInternalFrameAutorizacion(Gestor gestor) {
        this.gestor= gestor;
        this.setSize(400, 300);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNumeroSoli = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 22)); // NOI18N
        jLabel1.setText("Autorizar Tarjeta");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        jLabel2.setText("Ingrese el número de Solicitud:");

        jTextFieldNumeroSoli.setFont(new java.awt.Font("Century Gothic", 2, 15)); // NOI18N
        jTextFieldNumeroSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroSoliActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jToggleButton1.setText("Autorizar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextFieldNumeroSoli))
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumeroSoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumeroSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroSoliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroSoliActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        
                   
            try {
                int numeroSoli = Integer.parseInt(jTextFieldNumeroSoli.getText());
                
                Solicitudes soli = new Solicitudes(gestor);
                soli.autorizacionTarjeta(numeroSoli);
                this.setVisible(false);
            } catch (NumberFormatException e) {
                // Mostrar mensaje de error si el salario no es un número válido
                
                JOptionPane.showMessageDialog(
                    null,
                    "El Numero de Solicitud debe ser un número válido.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
                return; // Salir del método para evitar procesar datos incorrectos
            } 
     
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldNumeroSoli;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
